name: lovelace_website_env
channels:
  - defaults
dependencies:
  - appdirs=1.4.3=py37h28b3542_0
  - asn1crypto=0.24.0=py37_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py37_0
  - cffi=1.11.5=py37he75722e_1
  - chardet=3.0.4=py37_1
  - cryptography=2.3.1=py37hc365091_0
  - django=2.1.2=py37_0
  - idna=2.7=py37_0
  - krb5=1.16.1=hc83ff2d_6
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libpq=10.5=h1ad7b7a_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - ncurses=6.1=hf484d3e_0
  - openssl=1.0.2p=h14c3975_0
  - packaging=18.0=py37_0
  - pip=10.0.1=py37_0
  - psycopg2=2.7.5=py37hb7f436b_0
  - pycparser=2.19=py37_0
  - pyopenssl=18.0.0=py37_0
  - pyparsing=2.2.2=py37_0
  - pysocks=1.6.8=py37_0
  - python=3.7.0=h6e4f718_3
  - pytz=2018.5=py37_0
  - readline=7.0=h7b6447c_5
  - requests=2.19.1=py37_0
  - setuptools=40.4.3=py37_0
  - six=1.11.0=py37_1
  - sqlite=3.25.2=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - urllib3=1.23=py37_0
  - wheel=0.32.1=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
prefix: /root/anaconda3/envs/lovelace_website_env

